---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: localhost:5000/python-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "256Mi" # Minimum amount of memory guaranteed
            cpu: "500m" # Equivalent to 0.5 of a CPU
          limits:
            memory: "3Gi" # Maximum amount of memory the container can use
            cpu: "4" # Equivalent to 4 of a CPU

---
apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  namespace: python-app
spec:
  type: NodePort
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30800  # You can specify a port in the range 30000-32767
