name: Backend - E2E test

on:
  push:
    branches: ["*"]
    paths:
      - "assistant/backend/**"
  pull_request:
    branches: ["main"]
    paths:
      - "assistant/backend/**"

jobs:
  build:
    name: Backend E2E test
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      # Get the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Python 3.11
      - name: Install Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Pip settings
      - name: Set up pip
        run: |
          mkdir -p ~/.pip

          echo "${{ secrets.JFROG_IDENTITY_USER }}"
          echo "[global]" > ~/.pip/pip.conf
          echo "extra-index-url = https://${{ secrets.JFROG_IDENTITY_USER }}:${{ secrets.JFROG_IDENTITY_TOKEN }}@int.repositories.cloud.sap/artifactory/api/pypi/proxy-deploy-releases-hyperspace-pypi/simple" >> ~/.pip/pip.conf
          echo "trusted-host = int.repositories.cloud.sap" >> ~/.pip/pip.conf
          cat ~/.pip/pip.conf

      # Build local Docker image
      - name: Build Docker image
        run: |
          # Check Docker version
          docker --version

          # Enter the directory
          cd assistant/backend

          # Build the Docker image
          docker build -t ai-backend .

          cd ..
          cd ..
          # Check the Docker image
          docker images ai-backend

      # Install and configure K3s cluster
      - name: Install and configure K3s cluster
        run: |
          # K3s installation
          curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="v1.27.4+k3s1" K3S_KUBECONFIG_MODE=644 INSTALL_K3S_EXEC="server --docker --disable traefik" sh -
          mkdir -p ~/.kube
          cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
          chmod 600 ~/.kube/config

      # Verify K3s cluster
      - name: Verify K3s cluster
        run: |
          kubectl get nodes
          kubectl get pods --all-namespaces
