name: Backend - E2E test

on:
  push:
    branches: ["*"]
    paths:
      - "assistant/backend/**"
  pull_request:
    branches: ["main"]
    paths:
      - "assistant/backend/**"

jobs:
  build:
    name: Backend E2E test
    runs-on: self-hosted
    permissions: write-all
    steps:
      # Get the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Python 3.11
      - name: Install Python 3.11
        if: github.event_name != 'pull_request'
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - name: mydaemon
        run: |
          mkdir -p ~/.local/bin
          mkdir -p ~/.config/systemd/user
          cp scripts/mydaemon.sh ~/.local/bin/mydaemon.sh
          chmod +x ~/.local/bin/mydaemon.sh
          cp scripts/mydaemon.service ~/.config/systemd/user/mydaemon.service
          ls -la ~/.local/bin
          ls -la ~/.config/systemd/user
          loginctl enable-linger $USER
          export XDG_RUNTIME_DIR=/run/user/$(id -u)
          echo $XDG_RUNTIME_DIR

      - name: reload systemd user daemon
        run: |
          systemctl --user daemon-reload
      - name: run mydaemon
        run: |
          systemctl --user enable --now mydaemon.service
          systemctl --user start mydaemon.service
          systemctl --user status mydaemon.service
          sleep 5
          systemctl --user status mydaemon.service
          sleep 5
          systemctl --user status mydaemon.service
          sleep 5
          systemctl --user status mydaemon.service
          sleep 5


      - name: Download k3s binary
        run: |
          cat /etc/default/grub
          mkdir -p ~/.local/bin
          curl -sfL https://get.k3s.io -o ~/.local/bin/k3s
          chmod +x ~/.local/bin/k3s
    
      - name: Create systemd user service directory
        run: mkdir -p ~/.config/systemd/user
    
      - name: Download k3s-rootless.service file
        run: wget -P ~/.config/systemd/user/ https://raw.githubusercontent.com/k3s-io/k3s/v1.30.1-rc1%2Bk3s1/k3s-rootless.service
    
      - name: Modify k3s-rootless.service ExecStart line
        run: |
          sed -i 's|ExecStart=/usr/local/bin/k3s server --rootless|ExecStart=/home/runner/.local/bin/k3s server --rootless|' ~/.config/systemd/user/k3s-rootless.service
          cat ~/.config/systemd/user/k3s-rootless.service
    
      - name: Reload systemd user daemon
        run: |
          systemctl --user daemon-reload
    
      - name: Enable and start k3s service
        run: |
          systemctl --user enable --now k3s-rootless
          systemctl --user start k3s-rootless.service
    
      - name: Verify k3s service status
        run: systemctl --user status k3s-rootless.servic
      

      # Build local Docker image
      - name: Build Docker image
        if: github.event_name != 'pull_request'
        run: |
          # Check Docker version
          docker --version

          # Enter the directory
          cd assistant/flow

          # Build the Docker image
          docker build -t ai-backend .

          # Check the Docker image
          docker images ai-backend

      # Install and configure K3s cluster
      - name: Install and configure K3s cluster
        run: |
          # K3s installation
          curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="v1.27.4+k3s1" K3S_KUBECONFIG_MODE=644 INSTALL_K3S_EXEC="server --docker --disable traefik" sh -
          mkdir -p ~/.kube
          cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
          chmod 600 ~/.kube/config

      # Verify K3s cluster
      - name: Verify K3s cluster
        run: |
          kubectl get nodes
          kubectl get pods --all-namespaces
