name: "Companion E2E test"
run-name: "Companion E2E test - Phase 1"

# On Production you must use pull_request_target on main branch
# on:
#   pull_request_target:
#     branches:
#       - main
#     paths:
#       - "src/**"

on:
  pull_request:
    branches:
      - "*"
    paths:
      - "src/**"

# global env variables.
env:
  KYMA_VERSION: "2.20.5" # Kyma version.
  REPOSITORY_FULL_NAME: "${{ github.repository }}" # <owner>/<repository-name>.
  IMAGE_NAME: "europe-docker.pkg.dev/kyma-project/prod/kyma-companion" # without tag.

jobs:
  test-e2e:
    name: Run E2E tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Install Kyma CLI
        id: install-kyma-cli
        run: |
          mkdir -p bin
          curl -L "https://github.com/kyma-project/cli/releases/download/${KYMA_VERSION}/kyma_$(uname -s)_$(uname -m).tar.gz" | tar -zxvf - -C bin kyma && mv bin/kyma bin/kyma@v2
          $(pwd)/bin/kyma@v2 version
          status=$?
          echo "Command result: $status"
          if [ status -eq -1 ]; then
            
            echo "Failed to install Kyma CLI"
            exit 1
          else
            echo "Kyma CLI installed successfully"
          fi
