name: "Companion E2E test"
run-name: "Companion E2E test - Phase 1"

# On Production you must use pull_request_target on main branch
# on:
#   pull_request_target:
#     branches:
#       - main
#     paths:
#       - "src/**"

# on:
#   workflow_run:
#     workflows: [Pull Build Image]
#     types:
#       - completed

on:
  pull_request:
    branches:
      - "*"
    paths:
      - "src/**"

# global env variables.
env:
  DOCKER_TIMEOUT: 30
  KYMA_VERSION: "2.20.5" # Required Kyma version.
  K3D_VERSION: "v5.7.2" # Required K3d version.
  REPOSITORY_FULL_NAME: "${{ github.repository }}" # <owner>/<repository-name>.
  TRIGGER_ACTION_EVENT: "${{ github.event.action }}"
  IMAGE_NAME: "europe-docker.pkg.dev/kyma-project/prod/kyma-companion" # without tag.

jobs:
  test-e2e:
    name: Run E2E tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Install Kyma CLI
        id: install-kyma-cli
        run: |
          echo "${TRIGGER_ACTION_EVENT}"
          mkdir -p bin
          curl -L "https://github.com/kyma-project/cli/releases/download/${KYMA_VERSION}/kyma_$(uname -s)_$(uname -m).tar.gz" | tar -zxvf - -C bin kyma && mv bin/kyma bin/kyma@v2
          echo "::set-output name=version::$(bin/kyma@v2 version)"
        continue-on-error: true

      - name: Check Kyma CLI version
        id: check-kyma-cli-version
        run: |
          kyma_cli_version=$(echo "${{ steps.install-kyma-cli.outputs.version }}" | cut -d ":" -f 2 | xargs)
          if [ "$kyma_cli_version" != "${KYMA_VERSION}" ]; then
            echo "Kyma CLI version is not correct. Expected: ${KYMA_VERSION}, got: $kyma_cli_version"
            exit 1
          fi
          echo "Kyma CLI version is correct: $kyma_cli_version"

      - name: Install K3d
        id: install-k3d
        run: |
          curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | TAG=${K3D_VERSION} bash
          echo "::set-output name=version::$(k3d --version)"
        continue-on-error: true

      - name: Check K3d version
        id: check-k3d-version
        run: |
          k3d_version=$(echo "${{ steps.install-k3d.outputs.version }}" | cut -d " " -f 3 | xargs)
          if [ "$k3d_version" != "${K3D_VERSION}" ]; then
            echo "K3d version is not correct. Expected: ${K3D_VERSION}, got: $k3d_version"
            exit 1
          fi
          echo "K3d version is correct: $k3d_version"

      - name: Deploy Kyma
        id: deploy-kyma
        run: |
          echo "::group::Kyma - Provision"
          bin/kyma@v2 provision k3d --ci --non-interactive -p 9080:80@loadbalancer -p 9443:443@loadbalancer
          echo "::endgroup::"

          echo "::group::Kyma - Deploy"
          bin/kyma@v2 alpha deploy --ci --non-interactive
          echo "::endgroup::"

      - name: Verify Kyma deployment
        id: verify-kyma-deployment
        run: |
          echo "::group::Kyma - Context"
          context_name=$(kubectl config current-context)
          if [ "$context_name" != "k3d-kyma" ]; then
            echo "Kyma context is not correct. Expected: k3d-kyma, got: $context_name"
            exit 1
          fi
          echo "Kyma context is correct"
          echo "::endgroup::"

          echo "::group::Kyma - Verify Kyma deployment"
          kyma_status=$(kubectl get kyma -A -ojson | jq -r '[(.items[].status.state)] | .[0]')
          echo "::debug::Kyma status: $kyma_status"
          if [ "$kyma_status" != "Ready" ]; then
            echo "Kyma is not Ready. Expected: Ready, got: $kyma_status"
            exit 1
          fi
          echo "Kyma is Ready"
          echo "::endgroup::"

      - name: Companion Deploy - Create namespace
        id: companion-deploy-namespace
        run: |
          kubectl apply -f scripts/k8s/companion-namespace.yaml

      - name: Companion Deploy - Create secret on Kyma
        id: companion-deploy-secret
        run: |
          echo "${{ secrets.K3S_SECRET }}" > scripts/k8s/companiond-secret.yaml
          kubectl apply -f scripts/k8s/companiond-secret.yaml
          rm -f scripts/k8s/companiond-secret.yaml

      - name: Companion Deploy - Create configmap on Kyma
        id: companion-deploy-configmap
        run: |
          echo "${{ secrets.K3S_CONFIGMAP }}" > scripts/k8s/companiond-configmap.yaml
          kubectl apply -f scripts/k8s/companiond-configmap.yaml
          rm -f scripts/k8s/companiond-configmap.yaml

      - name: Companion Deploy - Create Backend and NodePort service
        id: companion-deploy-backend
        run: |
          kubectl apply -f scripts/k8s/companiond-deployment.yaml

      - name: Companion Deploy - Wait for deployment
        id: companion-deploy-wait
        run: scripts/shell/deploy-wait-for-deployment.sh $DOCKER_TIMEOUT
